---
name: build

on:
  push:
    branches:
      - trunk
      - release-*
    tags:
      - v*

  workflow_dispatch:

jobs:
  build:
    name: build_components
    runs-on: ubuntu-latest
    env:
      GOVER: 1.17

    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GOVER }}

      - name: write .netrc
        env:
          PAT: ${{ secrets.PAT_PHILLIP }}
        run: |
          echo "machine github.com login phillipleblanc password $PAT" > ~/.netrc

      - name: go get github.com/spiceai/spiceai
        env:
          GONOSUMDB: github.com/spiceai/spiceai
        run: go get github.com/spiceai/spiceai

      - name: go vet
        run: go vet ./...

      - name: go build
        run: go build ./...

      - name: go test
        run: go test ./...
