---
name: Check for forbidden licenses

# Checks for any forbidden/copyleft licenses using their SPDX identifiers
# (https://spdx.org/licenses/)

# To check Go modules, go-licenses (github.com/google/go-licenses) is used to
# generate a listing of packages and their associated licenses.  This listing is checked against a
# regex in FORBIDDEN_LICENSE_CHECK to ensure no forbidden licenses are present.  If any are detected, the build is failed.  

# List of copyleft licenses derived from Blue Oak Council Guide to Copyleft
# (https://blueoakcouncil.org/copyleft)

# List of forbidden licenses derived from Google License Classifier
# (https://github.com/google/licenseclassifier)

on:
  pull_request:
    branches:
      - trunk
      - release-*

jobs:
  license-check:
    name: license check
    runs-on: ubuntu-latest
    env:
      GOVER: 1.17
      FORBIDDEN_LICENSE_CHECK: |
        grep -E "GPL|CC-BY-SA|CC-BY-NC|CC-BY-NC-SA|CC-BY-NC-ND|APSL|CPAL|EUPL|NPOSL|OSL|SSPL|Parity|RPL|QPL|Sleepycat|copyleft|CDDL|CPL|EPL|ErlPL|IPL|MS-RL|SPL|Facebook|Commons-Clause" | grep . && exit 1 || echo "ok"

    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GOVER }}

      - name: Install go-licences
        run: go get github.com/google/go-licenses

      - name: Check dataconnector licenses
        working-directory: dataconnectors
        run: |
          go-licenses csv . |& ${{ env.FORBIDDEN_LICENSE_CHECK }}

      - name: Check dataprocessor licenses
        working-directory: dataprocessors
        run: |
          go-licenses csv . |& ${{ env.FORBIDDEN_LICENSE_CHECK }}
