---
name: pr_test

on:
  pull_request:
    branches:
      - trunk

jobs:
  go_test:
    name: go test
    runs-on: ubuntu-latest
    env:
      GOVER: 1.19

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GOVER }}

      - name: go vet
        run: go vet ./...

      - name: go test
        run: go test -v -shuffle=on -count=2 ./...
